version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT:-8000}:${PORT:-80}" # ใช้พอร์ตจาก environment variable
        environment:
            - PORT=10000 # ตั้งค่า PORT ใน environment ของ container
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
